sonar.projectKey=chapp-booking-engine
sonar.projectName=Chapp Booking Engine
sonar.projectVersion=1.0

sonar.sources=pms
sonar.tests=pms
sonar.test.inclusions=**/tests.py
sonar.exclusions=**/migrations/**,**/statics/**,**/templates/**

sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml

sonar.sourceEncoding=UTF-8
