# Generated by Django 4.2.29 on 2026-03-24 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0014_alter_booking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Formato de teléfono no válido. Ejemplo: +34 612 345 678', regex='^\\+?[\\d\\s\\-]{7,20}$')]),
        ),
    ]
